options:
  scss: '/code/guppy/public/css/scss'
  background-color: '#fff'
  base-font-size: 25px
  text-color: '#4e4e4e'
colors:
  red: '#FF5050'
  green: '#3688c2'
  blue: '#394e63'
  default: '#717171'
  success: '#5691CC'
  warning: '#4e4e4e'
  info: '#4d8cdf'
  light: '#fff'
controls:
  controls-depth: '2px'
  border-radius: '10px'
  controls-text-color: '#fff'
  controls-border-radius: '10px'
  controls-default-color: '#c3c3c3'
load-fonts:
  main-font: 'http://fonts.googleapis.com/css?family=Open+Sans:300&subset=latin,cyrillic'
  h-font: 'http://fonts.googleapis.com/css?family=Open+Sans:600&subset=latin,cyrillic'
  code-font: 'http://fonts.googleapis.com/css?family=Source+Code+Pro'
fonts:
  main-font-family: 'Open Sans'
  main-font-weight: '300'
  h-font-weight: '600'
  h-font-family: 'Open Sans'
  code-font-family: 'Source Code Pro'
responsive:
  tablet: '500px'
  mobile: '350px'
  wide: '900px'
